name: day3
description: Landing Page

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  fluttericon: ^1.0.7
  flare_flutter: ^2.0.5
  url_launcher: ^5.5.0
  url_launcher_web: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/